#!/usr/bin/env python3
import sys,bisect

def make_graph(N,M,a,b):
    G = [[] for i in range(N)]
    for j in range(M):
        G[a[j]-1].append(b[j]-1)
        G[b[j]-1].append(a[j]-1)
    for i in range(N):
      G[i] = list(set(G[i]))
    return G

def solve(N: int, M: int, a: "List[int]", b: "List[int]"):
    G = make_graph(N,M,a,b)
    res = 0
    for i in range(N):
        if G[i][0] < i :
            if  len(G[i]) == 1:
                res += 1
            else:
                if G[i][1] >= i:
                    res += 1
    return print(res)


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    a = [int()] * (M)  # type: "List[int]"
    b = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
    solve(N, M, a, b)

if __name__ == '__main__':
    main()
