#カテゴリとラベルは作った
# 後は頑張れ


# # プロンプト最終
# このコードの間違いを教えてください。
# 最後に以下のカテゴリのどれに当たるか数字のみ出力してください。
# 間違いの説明とカテゴリの出力のみ出力してください。
aa_cluster_categories = {
    "1": "ハッシュ衝突",
    "2": "二分探索関連の間違い",
    "3": "出力位置間違い",
    "4": "名簿管理での間違い",
    "5": "重複チェックでの間違い"
}

aa_cluster_label = {
    "submission_1": "",
    "submission_2": "",
    "submission_3": "",
    "submission_4": "",
    "submission_5": "",
    "submission_6": "",
    "submission_7": "",
    "submission_8": "",
    "submission_9": "",
    "submission_10": "",
    "submission_11": "",
    "submission_12": "",
    "submission_13": "",
    "submission_14": "",
    "submission_15": "",
    "submission_16": "",
    "submission_17": "",
    "submission_18": "",
    "submission_19": "",
    "submission_20": "",
    "submission_21": "",
    "submission_22": "",
    "submission_23": "",
    "submission_24": "",
    "submission_25": "",
    "submission_26": "",
    "submission_27": "",
    "submission_28": "",
    "submission_29": "",
    "submission_30": "",
    "submission_31": "",
    "submission_32": "",
    "submission_33": "",
    "submission_34": "",
    "submission_35": "",
    "submission_36": "",
    "submission_37": "",
    "submission_38": "",
    "submission_39": "",
    "submission_40": "",
    "submission_41": "",
    "submission_42": "",
    "submission_43": "",
    "submission_44": "",
    "submission_45": "",
    "submission_46": "",
    "submission_47": "",
    "submission_48": "",
    "submission_49": "",
    "submission_50": "",
    "submission_51": "",
    "submission_52": "",
    "submission_53": "",
    "submission_54": "",
    "submission_55": "",
    "submission_56": "",
    "submission_57": "",
    "submission_58": "",
    "submission_59": "",
    "submission_60": "",
    "submission_61": "",
    "submission_62": "",
    "submission_63": "",
    "submission_64": "",
    "submission_65": "",
    "submission_66": "",
    "submission_67": "",
    "submission_68": "",
    "submission_69": "",
    "submission_70": "",
    "submission_71": "",
    "submission_72": "",
    "submission_73": "",
    "submission_74": "",
    "submission_75": "",
    "submission_76": "",
    "submission_77": "",
    "submission_78": "",
    "submission_79": "",
    "submission_80": "",
    "submission_81": "",
    "submission_82": "",
    "submission_83": "",
    "submission_84": "",
    "submission_85": "",
    "submission_86": "",
    "submission_87": "",
    "submission_88": "",
    "submission_89": "",
    "submission_90": "",
    "submission_91": "",
    "submission_92": "",
    "submission_93": "",
    "submission_94": "",
    "submission_95": "",
    "submission_96": "",
    "submission_97": "",
    "submission_98": "",
    "submission_99": "",
    "submission_100": ""
}

ag_cluster_categories = {
    "1": "for文で検索してる",
    "2": "考慮漏れによる間違い"
}


ag_cluster_label = {
    "submission_1": "",
    "submission_2": "",
    "submission_3": "",
    "submission_4": "",
    "submission_5": "",
    "submission_6": "",
    "submission_7": "",
    "submission_8": "",
    "submission_9": "",
    "submission_10": "",
    "submission_11": "",
    "submission_12": "",
    "submission_13": "",
    "submission_14": "",
    "submission_15": "",
    "submission_16": "",
    "submission_17": "",
    "submission_18": "",
    "submission_19": "",
    "submission_20": "",
    "submission_21": "",
    "submission_22": "",
    "submission_23": "",
    "submission_24": "",
    "submission_25": "",
    "submission_26": "",
    "submission_27": "",
    "submission_28": "",
    "submission_29": "",
    "submission_30": "",
    "submission_31": "",
    "submission_32": "",
    "submission_33": "",
    "submission_34": "",
    "submission_35": "",
    "submission_36": "",
    "submission_37": "",
    "submission_38": "",
    "submission_39": "",
    "submission_40": "",
    "submission_41": "",
    "submission_42": "",
    "submission_43": "",
    "submission_44": "",
    "submission_45": "",
    "submission_46": "",
    "submission_47": "",
    "submission_48": "",
    "submission_49": "",
    "submission_50": "",
    "submission_51": "",
    "submission_52": "",
    "submission_53": "",
    "submission_54": "",
    "submission_55": "",
    "submission_56": "",
    "submission_57": "",
    "submission_58": "",
    "submission_59": "",
    "submission_60": "",
    "submission_61": "",
    "submission_62": "",
    "submission_63": "",
    "submission_64": "",
    "submission_65": "",
    "submission_66": "",
    "submission_67": "",
    "submission_68": "",
    "submission_69": "",
    "submission_70": "",
    "submission_71": "",
    "submission_72": "",
    "submission_73": "",
    "submission_74": "",
    "submission_75": "",
    "submission_76": "",
    "submission_77": "",
    "submission_78": "",
    "submission_79": "",
    "submission_80": "",
    "submission_81": "",
    "submission_82": "",
    "submission_83": "",
    "submission_84": "",
    "submission_85": "",
    "submission_86": "",
    "submission_87": "",
    "submission_88": "",
    "submission_89": "",
    "submission_90": "",
    "submission_91": "",
    "submission_92": "",
    "submission_93": "",
    "submission_94": "",
    "submission_95": "",
    "submission_96": "",
    "submission_97": "",
    "submission_98": "",
    "submission_99": "",
    "submission_100": ""
}

bc_cluster_categories = {
    "1": "全パターン検索",
    "2": "組み合わせはいいけど計算が何かしら間違っている",
    "3": "組み合わせ作成や選択間違い",
    "4": "計算以外の条件確認間違い",
    "5": "計算方法はあってるけど剰余計算のところで何かしらエラー"
}


bc_cluster_label = {
    "submission_1": "",
    "submission_2": "",
    "submission_3": "",
    "submission_4": "",
    "submission_5": "",
    "submission_6": "",
    "submission_7": "",
    "submission_8": "",
    "submission_9": "",
    "submission_10": "",
    "submission_11": "",
    "submission_12": "",
    "submission_13": "",
    "submission_14": "",
    "submission_15": "",
    "submission_16": "",
    "submission_17": "",
    "submission_18": "",
    "submission_19": "",
    "submission_20": "",
    "submission_21": "",
    "submission_22": "",
    "submission_23": "",
    "submission_24": "",
    "submission_25": "",
    "submission_26": "",
    "submission_27": "",
    "submission_28": "",
    "submission_29": "",
    "submission_30": "",
    "submission_31": "",
    "submission_32": "",
    "submission_33": "",
    "submission_34": "",
    "submission_35": "",
    "submission_36": "",
    "submission_37": "",
    "submission_38": "",
    "submission_39": "",
    "submission_40": "",
    "submission_41": "",
    "submission_42": "",
    "submission_43": "",
    "submission_44": "",
    "submission_45": "",
    "submission_46": "",
    "submission_47": "",
    "submission_48": "",
    "submission_49": "",
    "submission_50": "",
    "submission_51": "",
    "submission_52": "",
    "submission_53": "",
    "submission_54": "",
    "submission_55": "",
    "submission_56": "",
    "submission_57": "",
    "submission_58": "",
    "submission_59": "",
    "submission_60": "",
    "submission_61": "",
    "submission_62": "",
    "submission_63": "",
    "submission_64": "",
    "submission_65": "",
    "submission_66": "",
    "submission_67": "",
    "submission_68": "",
    "submission_69": "",
    "submission_70": "",
    "submission_71": "",
    "submission_72": "",
    "submission_73": "",
    "submission_74": "",
    "submission_75": "",
    "submission_76": "",
    "submission_77": "",
    "submission_78": "",
    "submission_79": "",
    "submission_80": "",
    "submission_81": "",
    "submission_82": "",
    "submission_83": "",
    "submission_84": "",
    "submission_85": "",
    "submission_86": "",
    "submission_87": "",
    "submission_88": "",
    "submission_89": "",
    "submission_90": "",
    "submission_91": "",
    "submission_92": "",
    "submission_93": "",
    "submission_94": "",
    "submission_95": "",
    "submission_96": "",
    "submission_97": "",
    "submission_98": "",
    "submission_99": "",
    "submission_100": ""
}

bi_cluster_categories = {
    "1": "出力のインデックス関連エラー",
    "2": "山札操作関連エラー"
}


bi_cluster_label = {
    "submission_1": "",
    "submission_2": "",
    "submission_3": "",
    "submission_4": "",
    "submission_5": "",
    "submission_6": "",
    "submission_7": "",
    "submission_8": "",
    "submission_9": "",
    "submission_10": "",
    "submission_11": "",
    "submission_12": "",
    "submission_13": "",
    "submission_14": "",
    "submission_15": "",
    "submission_16": "",
    "submission_17": "",
    "submission_18": "",
    "submission_19": "",
    "submission_20": "",
    "submission_21": "",
    "submission_22": "",
    "submission_23": "",
    "submission_24": "",
    "submission_25": "",
    "submission_26": "",
    "submission_27": "",
    "submission_28": "",
    "submission_29": "",
    "submission_30": "",
    "submission_31": "",
    "submission_32": "",
    "submission_33": "",
    "submission_34": "",
    "submission_35": "",
    "submission_36": "",
    "submission_37": "",
    "submission_38": "",
    "submission_39": "",
    "submission_40": "",
    "submission_41": "",
    "submission_42": "",
    "submission_43": "",
    "submission_44": "",
    "submission_45": "",
    "submission_46": "",
    "submission_47": "",
    "submission_48": "",
    "submission_49": "",
    "submission_50": "",
    "submission_51": "",
    "submission_52": "",
    "submission_53": "",
    "submission_54": "",
    "submission_55": "",
    "submission_56": "",
    "submission_57": "",
    "submission_58": "",
    "submission_59": "",
    "submission_60": "",
    "submission_61": "",
    "submission_62": "",
    "submission_63": "",
    "submission_64": "",
    "submission_65": "",
    "submission_66": "",
    "submission_67": "",
    "submission_68": "",
    "submission_69": "",
    "submission_70": "",
    "submission_71": "",
    "submission_72": "",
    "submission_73": "",
    "submission_74": "",
    "submission_75": "",
    "submission_76": "",
    "submission_77": "",
    "submission_78": "",
    "submission_79": "",
    "submission_80": "",
    "submission_81": "",
    "submission_82": "",
    "submission_83": "",
    "submission_84": "",
    "submission_85": "",
    "submission_86": "",
    "submission_87": "",
    "submission_88": "",
    "submission_89": "",
    "submission_90": "",
    "submission_91": "",
    "submission_92": "",
    "submission_93": "",
    "submission_94": "",
    "submission_95": "",
    "submission_96": "",
    "submission_97": "",
    "submission_98": "",
    "submission_99": "",
    "submission_100": ""
}

bo_cluster_categories = {
    "1": "N=0の処理漏れ",
    "2": "再帰して計算エラー",
    "3": "出力間違い",
    "4": "進数変換処理中にエラー"

}

bo_cluster_label = {
    "submission_1": "",
    "submission_2": "",
    "submission_3": "",
    "submission_4": "",
    "submission_5": "",
    "submission_6": "",
    "submission_7": "",
    "submission_8": "",
    "submission_9": "",
    "submission_10": "",
    "submission_11": "",
    "submission_12": "",
    "submission_13": "",
    "submission_14": "",
    "submission_15": "",
    "submission_16": "",
    "submission_17": "",
    "submission_18": "",
    "submission_19": "",
    "submission_20": "",
    "submission_21": "",
    "submission_22": "",
    "submission_23": "",
    "submission_24": "",
    "submission_25": "",
    "submission_26": "",
    "submission_27": "",
    "submission_28": "",
    "submission_29": "",
    "submission_30": "",
    "submission_31": "",
    "submission_32": "",
    "submission_33": "",
    "submission_34": "",
    "submission_35": "",
    "submission_36": "",
    "submission_37": "",
    "submission_38": "",
    "submission_39": "",
    "submission_40": "",
    "submission_41": "",
    "submission_42": "",
    "submission_43": "",
    "submission_44": "",
    "submission_45": "",
    "submission_46": "",
    "submission_47": "",
    "submission_48": "",
    "submission_49": "",
    "submission_50": "",
    "submission_51": "",
    "submission_52": "",
    "submission_53": "",
    "submission_54": "",
    "submission_55": "",
    "submission_56": "",
    "submission_57": "",
    "submission_58": "",
    "submission_59": "",
    "submission_60": "",
    "submission_61": "",
    "submission_62": "",
    "submission_63": "",
    "submission_64": "",
    "submission_65": "",
    "submission_66": "",
    "submission_67": "",
    "submission_68": "",
    "submission_69": "",
    "submission_70": "",
    "submission_71": "",
    "submission_72": "",
    "submission_73": "",
    "submission_74": "",
    "submission_75": "",
    "submission_76": "",
    "submission_77": "",
    "submission_78": "",
    "submission_79": "",
    "submission_80": "",
    "submission_81": "",
    "submission_82": "",
    "submission_83": "",
    "submission_84": "",
    "submission_85": "",
    "submission_86": "",
    "submission_87": "",
    "submission_88": "",
    "submission_89": "",
    "submission_90": "",
    "submission_91": "",
    "submission_92": "",
    "submission_93": "",
    "submission_94": "",
    "submission_95": "",
    "submission_96": "",
    "submission_97": "",
    "submission_98": "",
    "submission_99": "",
    "submission_100": ""
}

bz_cluster_categories = {
    "1": "グラフ作って探索しTLE",
    "2": "ちょうど1個のカウントができていない",
    "3": "隣接している配列作成に関する間違い"
}

bz_cluster_label = {
    "submission_1": "",
    "submission_2": "",
    "submission_3": "",
    "submission_4": "",
    "submission_5": "",
    "submission_6": "",
    "submission_7": "",
    "submission_8": "",
    "submission_9": "",
    "submission_10": "",
    "submission_11": "",
    "submission_12": "",
    "submission_13": "",
    "submission_14": "",
    "submission_15": "",
    "submission_16": "",
    "submission_17": "",
    "submission_18": "",
    "submission_19": "",
    "submission_20": "",
    "submission_21": "",
    "submission_22": "",
    "submission_23": "",
    "submission_24": "",
    "submission_25": "",
    "submission_26": "",
    "submission_27": "",
    "submission_28": "",
    "submission_29": "",
    "submission_30": "",
    "submission_31": "",
    "submission_32": "",
    "submission_33": "",
    "submission_34": "",
    "submission_35": "",
    "submission_36": "",
    "submission_37": "",
    "submission_38": "",
    "submission_39": "",
    "submission_40": "",
    "submission_41": "",
    "submission_42": "",
    "submission_43": "",
    "submission_44": "",
    "submission_45": "",
    "submission_46": "",
    "submission_47": "",
    "submission_48": "",
    "submission_49": "",
    "submission_50": "",
    "submission_51": "",
    "submission_52": "",
    "submission_53": "",
    "submission_54": "",
    "submission_55": "",
    "submission_56": "",
    "submission_57": "",
    "submission_58": "",
    "submission_59": "",
    "submission_60": "",
    "submission_61": "",
    "submission_62": "",
    "submission_63": "",
    "submission_64": "",
    "submission_65": "",
    "submission_66": "",
    "submission_67": "",
    "submission_68": "",
    "submission_69": "",
    "submission_70": "",
    "submission_71": "",
    "submission_72": "",
    "submission_73": "",
    "submission_74": "",
    "submission_75": "",
    "submission_76": "",
    "submission_77": "",
    "submission_78": "",
    "submission_79": "",
    "submission_80": "",
    "submission_81": "",
    "submission_82": "",
    "submission_83": "",
    "submission_84": "",
    "submission_85": "",
    "submission_86": "",
    "submission_87": "",
    "submission_88": "",
    "submission_89": "",
    "submission_90": "",
    "submission_91": "",
    "submission_92": "",
    "submission_93": "",
    "submission_94": "",
    "submission_95": "",
    "submission_96": "",
    "submission_97": "",
    "submission_98": "",
    "submission_99": "",
    "submission_100": ""
}

d_cluster_categories = {
    "1": "出力のインデックス間違い",
    "2": "累積和作成で間違い",
    "3": "累積和使用していない",
    "4": "累積和使用しているけど計算方法間違い"
}

d_cluster_label = {
    "submission_1": "",
    "submission_2": "",
    "submission_3": "",
    "submission_4": "",
    "submission_5": "",
    "submission_6": "",
    "submission_7": "",
    "submission_8": "",
    "submission_9": "",
    "submission_10": "",
    "submission_11": "",
    "submission_12": "",
    "submission_13": "",
    "submission_14": "",
    "submission_15": "",
    "submission_16": "",
    "submission_17": "",
    "submission_18": "",
    "submission_19": "",
    "submission_20": "",
    "submission_21": "",
    "submission_22": "",
    "submission_23": "",
    "submission_24": "",
    "submission_25": "",
    "submission_26": "",
    "submission_27": "",
    "submission_28": "",
    "submission_29": "",
    "submission_30": "",
    "submission_31": "",
    "submission_32": "",
    "submission_33": "",
    "submission_34": "",
    "submission_35": "",
    "submission_36": "",
    "submission_37": "",
    "submission_38": "",
    "submission_39": "",
    "submission_40": "",
    "submission_41": "",
    "submission_42": "",
    "submission_43": "",
    "submission_44": "",
    "submission_45": "",
    "submission_46": "",
    "submission_47": "",
    "submission_48": "",
    "submission_49": "",
    "submission_50": "",
    "submission_51": "",
    "submission_52": "",
    "submission_53": "",
    "submission_54": "",
    "submission_55": "",
    "submission_56": "",
    "submission_57": "",
    "submission_58": "",
    "submission_59": "",
    "submission_60": "",
    "submission_61": "",
    "submission_62": "",
    "submission_63": "",
    "submission_64": "",
    "submission_65": "",
    "submission_66": "",
    "submission_67": "",
    "submission_68": "",
    "submission_69": "",
    "submission_70": "",
    "submission_71": "",
    "submission_72": "",
    "submission_73": "",
    "submission_74": "",
    "submission_75": "",
    "submission_76": "",
    "submission_77": "",
    "submission_78": "",
    "submission_79": "",
    "submission_80": "",
    "submission_81": "",
    "submission_82": "",
    "submission_83": "",
    "submission_84": "",
    "submission_85": "",
    "submission_86": "",
    "submission_87": "",
    "submission_88": "",
    "submission_89": "",
    "submission_90": "",
    "submission_91": "",
    "submission_92": "",
    "submission_93": "",
    "submission_94": "",
    "submission_95": "",
    "submission_96": "",
    "submission_97": "",
    "submission_98": "",
    "submission_99": "",
    "submission_100": ""
}

j_cluster_categories = {
    "1": "インデックス以外のクエリ処理での間違い",
    "2": "クエリ処理時のインデックス処理での間違い",
    "3": "累積和作成での間違い",
    "4": "累積和使っていない",
    "5": "結果の計算間違い"
}

j_cluster_label = {
    "submission_1": "",
    "submission_2": "",
    "submission_3": "",
    "submission_4": "",
    "submission_5": "",
    "submission_6": "",
    "submission_7": "",
    "submission_8": "",
    "submission_9": "",
    "submission_10": "",
    "submission_11": "",
    "submission_12": "",
    "submission_13": "",
    "submission_14": "",
    "submission_15": "",
    "submission_16": "",
    "submission_17": "",
    "submission_18": "",
    "submission_19": "",
    "submission_20": "",
    "submission_21": "",
    "submission_22": "",
    "submission_23": "",
    "submission_24": "",
    "submission_25": "",
    "submission_26": "",
    "submission_27": "",
    "submission_28": "",
    "submission_29": "",
    "submission_30": "",
    "submission_31": "",
    "submission_32": "",
    "submission_33": "",
    "submission_34": "",
    "submission_35": "",
    "submission_36": "",
    "submission_37": "",
    "submission_38": "",
    "submission_39": "",
    "submission_40": "",
    "submission_41": "",
    "submission_42": "",
    "submission_43": "",
    "submission_44": "",
    "submission_45": "",
    "submission_46": "",
    "submission_47": "",
    "submission_48": "",
    "submission_49": "",
    "submission_50": "",
    "submission_51": "",
    "submission_52": "",
    "submission_53": "",
    "submission_54": "",
    "submission_55": "",
    "submission_56": "",
    "submission_57": "",
    "submission_58": "",
    "submission_59": "",
    "submission_60": "",
    "submission_61": "",
    "submission_62": "",
    "submission_63": "",
    "submission_64": "",
    "submission_65": "",
    "submission_66": "",
    "submission_67": "",
    "submission_68": "",
    "submission_69": "",
    "submission_70": "",
    "submission_71": "",
    "submission_72": "",
    "submission_73": "",
    "submission_74": "",
    "submission_75": "",
    "submission_76": "",
    "submission_77": "",
    "submission_78": "",
    "submission_79": "",
    "submission_80": "",
    "submission_81": "",
    "submission_82": "",
    "submission_83": "",
    "submission_84": "",
    "submission_85": "",
    "submission_86": "",
    "submission_87": "",
    "submission_88": "",
    "submission_89": "",
    "submission_90": "",
    "submission_91": "",
    "submission_92": "",
    "submission_93": "",
    "submission_94": "",
    "submission_95": "",
    "submission_96": "",
    "submission_97": "",
    "submission_98": "",
    "submission_99": "",
    "submission_100": ""
}

v_cluster_categories = {
    "1": "実際に切ってカウントする間違い",
    "2": "最大公約数算出間違い",
    "3": "浮動小数誤差による間違い",
    "4": "計算回数算出間違い"
}

v_cluster_label = {
    "submission_1": "",
    "submission_2": "",
    "submission_3": "",
    "submission_4": "",
    "submission_5": "",
    "submission_6": "",
    "submission_7": "",
    "submission_8": "",
    "submission_9": "",
    "submission_10": "",
    "submission_11": "",
    "submission_12": "",
    "submission_13": "",
    "submission_14": "",
    "submission_15": "",
    "submission_16": "",
    "submission_17": "",
    "submission_18": "",
    "submission_19": "",
    "submission_20": "",
    "submission_21": "",
    "submission_22": "",
    "submission_23": "",
    "submission_24": "",
    "submission_25": "",
    "submission_26": "",
    "submission_27": "",
    "submission_28": "",
    "submission_29": "",
    "submission_30": "",
    "submission_31": "",
    "submission_32": "",
    "submission_33": "",
    "submission_34": "",
    "submission_35": "",
    "submission_36": "",
    "submission_37": "",
    "submission_38": "",
    "submission_39": "",
    "submission_40": "",
    "submission_41": "",
    "submission_42": "",
    "submission_43": "",
    "submission_44": "",
    "submission_45": "",
    "submission_46": "",
    "submission_47": "",
    "submission_48": "",
    "submission_49": "",
    "submission_50": "",
    "submission_51": "",
    "submission_52": "",
    "submission_53": "",
    "submission_54": "",
    "submission_55": "",
    "submission_56": "",
    "submission_57": "",
    "submission_58": "",
    "submission_59": "",
    "submission_60": "",
    "submission_61": "",
    "submission_62": "",
    "submission_63": "",
    "submission_64": "",
    "submission_65": "",
    "submission_66": "",
    "submission_67": "",
    "submission_68": "",
    "submission_69": "",
    "submission_70": "",
    "submission_71": "",
    "submission_72": "",
    "submission_73": "",
    "submission_74": "",
    "submission_75": "",
    "submission_76": "",
    "submission_77": "",
    "submission_78": "",
    "submission_79": "",
    "submission_80": "",
    "submission_81": "",
    "submission_82": "",
    "submission_83": "",
    "submission_84": "",
    "submission_85": "",
    "submission_86": "",
    "submission_87": "",
    "submission_88": "",
    "submission_89": "",
    "submission_90": "",
    "submission_91": "",
    "submission_92": "",
    "submission_93": "",
    "submission_94": "",
    "submission_95": "",
    "submission_96": "",
    "submission_97": "",
    "submission_98": "",
    "submission_99": "",
    "submission_100": ""
}

x_cluster_categories = {
    "1": "判定条件の計算間違い",
    "2": "判定条件漏れ",
    "3": "判定条件漏れ以外の条件に関する間違い",
    "4": "差分の計算間違い"
}

x_cluster_label = {
    "submission_1": "",
    "submission_2": "",
    "submission_3": "",
    "submission_4": "",
    "submission_5": "",
    "submission_6": "",
    "submission_7": "",
    "submission_8": "",
    "submission_9": "",
    "submission_10": "",
    "submission_11": "",
    "submission_12": "",
    "submission_13": "",
    "submission_14": "",
    "submission_15": "",
    "submission_16": "",
    "submission_17": "",
    "submission_18": "",
    "submission_19": "",
    "submission_20": "",
    "submission_21": "",
    "submission_22": "",
    "submission_23": "",
    "submission_24": "",
    "submission_25": "",
    "submission_26": "",
    "submission_27": "",
    "submission_28": "",
    "submission_29": "",
    "submission_30": "",
    "submission_31": "",
    "submission_32": "",
    "submission_33": "",
    "submission_34": "",
    "submission_35": "",
    "submission_36": "",
    "submission_37": "",
    "submission_38": "",
    "submission_39": "",
    "submission_40": "",
    "submission_41": "",
    "submission_42": "",
    "submission_43": "",
    "submission_44": "",
    "submission_45": "",
    "submission_46": "",
    "submission_47": "",
    "submission_48": "",
    "submission_49": "",
    "submission_50": "",
    "submission_51": "",
    "submission_52": "",
    "submission_53": "",
    "submission_54": "",
    "submission_55": "",
    "submission_56": "",
    "submission_57": "",
    "submission_58": "",
    "submission_59": "",
    "submission_60": "",
    "submission_61": "",
    "submission_62": "",
    "submission_63": "",
    "submission_64": "",
    "submission_65": "",
    "submission_66": "",
    "submission_67": "",
    "submission_68": "",
    "submission_69": "",
    "submission_70": "",
    "submission_71": "",
    "submission_72": "",
    "submission_73": "",
    "submission_74": "",
    "submission_75": "",
    "submission_76": "",
    "submission_77": "",
    "submission_78": "",
    "submission_79": "",
    "submission_80": "",
    "submission_81": "",
    "submission_82": "",
    "submission_83": "",
    "submission_84": "",
    "submission_85": "",
    "submission_86": "",
    "submission_87": "",
    "submission_88": "",
    "submission_89": "",
    "submission_90": "",
    "submission_91": "",
    "submission_92": "",
    "submission_93": "",
    "submission_94": "",
    "submission_95": "",
    "submission_96": "",
    "submission_97": "",
    "submission_98": "",
    "submission_99": "",
    "submission_100": ""
}

import os
import shutil

def organize_files_by_category(source_directory, categories, submission_labels):
    """
    指定されたディレクトリのファイルをカテゴリごとに仕分けする

    Args:
        source_directory (str): 元のディレクトリパス
        categories (dict): カテゴリの辞書（key: カテゴリ番号, value: カテゴリ名）
        submission_labels (dict): ファイルとカテゴリの対応（key: ファイル名（.py無し）, value: カテゴリ番号）
    """
    # 出力ディレクトリを作成
    output_directory = source_directory + "_gpt_cluster"
    if not os.path.exists(output_directory):
        os.makedirs(output_directory)
        print(f"作成されたディレクトリ: {output_directory}")

    # カテゴリディレクトリを作成
    category_dirs = {}
    category_file_counts = {}
    for key, value in categories.items():
        category_dir = os.path.join(output_directory, f"pattern_{key}_{value}")
        if not os.path.exists(category_dir):
            os.makedirs(category_dir)
            print(f"作成されたカテゴリディレクトリ: {category_dir}")
        category_dirs[key] = category_dir
        category_file_counts[key] = 0

    # ファイルを仕分け
    for filename, category_id in submission_labels.items():
        source_file = os.path.join(source_directory, f"{filename}.py")

        if os.path.exists(source_file):
            if category_id in category_dirs:
                destination_file = os.path.join(category_dirs[category_id], f"{filename}.py")
                shutil.copy2(source_file, destination_file)
                category_file_counts[category_id] += 1
                print(f"コピー完了: {source_file} -> {destination_file}")
            else:
                print(f"警告: カテゴリID '{category_id}' が見つかりません - ファイル: {filename}")
        else:
            print(f"警告: ファイルが見つかりません - {source_file}")

    # ディレクトリごとのファイル数を表示
    print("\n" + "=" * 50)
    print("カテゴリ別ファイル数統計")
    print("=" * 50)
    total_files = 0
    for key, value in categories.items():
        count = category_file_counts[key]
        total_files += count
        print(f"カテゴリ {key} ({value}): {count} ファイル")
    
    print("-" * 50)
    print(f"合計: {total_files} ファイル")

def main():
    """
    メイン処理
    ユーザーに対象ディレクトリを入力してもらい、ファイルの仕分けを実行
    """
    print("ファイル仕分けツール")
    print("=" * 50)

    # ディレクトリの入力
    source_directory = input("対象ディレクトリのパスを入力してください: ").strip()

    if not os.path.exists(source_directory):
        print(f"エラー: ディレクトリ '{source_directory}' が見つかりません")
        return

    print(f"\n対象ディレクトリ: {source_directory}")
    print(f"出力ディレクトリ: {source_directory}_gpt_cluster")

    # 仕分け処理の実行
    organize_files_by_category(source_directory, bo_cluster_categories, bo_submission_labels)

    print("\n仕分け処理が完了しました！")

if __name__ == "__main__":
    main()



